name: 'Phpcs and reviewdog runner'
description: 'This action installs reviewdog 🐶, runs phpcs 🐘 and pipes output to reviewdog. It depends '
inputs:
  reviewdog_token:
    description: 'The Github API token needed for Reviewdog'
  path:
    description: 'What is the base path (where phpcs config file and composer.json is)?'
    required: false
    default: '.'
  phpcs_path:
    description: 'Which directory should phpcs be sniffing?'
    required: false
    default: '.'
 
runs:
  using: 'composite'
  steps:
    - name: Install reviewdog
      run: $GITHUB_ACTION_PATH/install.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: v0.13.0
        REVIEWDOG_TEMPDIR: ${{ runner.temp }}
    - name: Run phpcs and report to reviewdog
      run: |
        set +o pipefail

        cd ${{ inputs.path }}

        # No warnings errors/warnings since it breaks the connection to reviewdog.
        $(composer config bin-dir)/phpcs --config-set ignore_errors_on_exit 1
        $(composer config bin-dir)/phpcs --config-set ignore_warnings_on_exit 1

        # Run code sniffer.
        $(composer config bin-dir)/phpcs --report=checkstyle ${{ inputs.phpcs_path }} \
        | reviewdog -f=checkstyle -name=phpcs -reporter=github-pr-check -fail-on-error=true
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.reviewdog_token }}

branding:
  icon: 'terminal'
  color: 'gray-dark'
